### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [kkehe/PicoAltoids#1]
Hello!

I found your project from https://hackaday.com/2022/06/07/a-breath-of-fresh-air-for-some-arcade-classics/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code, PCB files and images in any purpose?
It would be great to see any popular open source license.

**Comment by kaydenkehe** [comment]
Yes! Anyone is allowed to do whatever they please with this project. I've never licensed a project before, so I'll try to find the appropriate license and add it. :)

**Comment by vazhnov** [comment]
> Anyone is allowed to do whatever they please with this project.

Sounds like MIT or BSD license :)

**Comment by vazhnov** [comment]
MIT — cool! @kkehe, thank you!
